### ISSUE TITLE
搜索完成后回车不会进入zeal程序搜索/Press ‘Enter’ after search will not goto Zeal program search

### ISSUE THREAD

**Issue by sundxfansky** [yar999/Wox-Dash-Zeal#1]
在搜索到指定条目后，回车不会出现示意图的情况
after search the item，press enter will not go to the zeal program as the example-gif shows

**Comment by sundxfansky** [comment]
对应到(refer to) main.py line20 "dash://"

**Comment by sundxfansky** [comment]
搞定了 
首先注意在 docs.py 文件中需要修改30 行和32行的数字4，换成自己对应zeal程序doc文件所在的对应第几个子文件夹数目，可以解决图标以及title显示不正确的问题，其次在main程序中 修改def zeal 函数

import subprocess
subprocess.Popen('YOUR ZEAL.EXE PATH {}'.format(query))

**Comment by yar999** [comment]
zeal安装好之后会自动注册 `dash://` 和 `dash-plugin://` 协议
