### ISSUE TITLE
Can't open zeal when enter z into wox

### ISSUE THREAD

**Issue by zhangchengshan** [yar999/Wox-Dash-Zeal#2]
i have update docspath.json, but wox don't show zeal when enter z.
![image](https://user-images.githubusercontent.com/6310213/50873989-38140300-13fd-11e9-8f99-d14431b07b42.png)
![image](https://user-images.githubusercontent.com/6310213/50874845-9ee6eb80-1400-11e9-83e7-598d2a4845af.png)

**Comment by yar999** [comment]
please check logs in `C:\Users\<your username>\AppData\Roaming\Wox\Logs\1.3.524`

@zhangchengshan

**Comment by zhangchengshan** [comment]
thanks, the log is very useful. i will close this issue.
