### ISSUE TITLE
Always searches Local

### ISSUE THREAD

**Issue by mi5ha** [yar999/Wox-Dash-Zeal#3]
Hi there, I cant seem to be able to search any docset except Local? I added aliases, still nothing.

![image](https://user-images.githubusercontent.com/1238203/52332833-08f0b180-29fc-11e9-9e2d-0a26d1075f07.png)

**Comment by kkzzhizhou** [comment]
搜索修改docs.py文件
pl = db.split(os.path.sep)[4].split('.')[0]
修改为：
pl = db.split(os.path.sep)[8].split('.')[0]

**Comment by yar999** [comment]
plugin directory docspath.json default :
```
{
    "path": "D:\\Program Files\\Zeal\\dossets"
}
```
Modify according to the actual situation
