### ISSUE TITLE
docset icon and query string mismatch

### ISSUE THREAD

**Issue by pnck** [yar999/Wox-Dash-Zeal#4]
[![issue.png](https://i.loli.net/2019/04/14/5cb33e44c539e.png)](https://i.loli.net/2019/04/14/5cb33e44c539e.png)

**Comment by yar999** [comment]
It's probably the problem with the docset you installed.

**Comment by yar999** [comment]
Make sure docset paths are configured correctly in docspath.json

```
> python docs.py c++:std::cout
[{'img': 'D:\\Program Files\\Zeal\\dossets\\C++.docset\\icon@2x.png',
  'pl': 'C++',
  'res': 'std::cout, std::wcout'}]
```
